<?php
/**
 * Created by PhpStorm.
 * User: stretch
 * Date: 4/10/18
 * Time: 9:14 PM
 */

namespace Plaid\Metadata;


class InstitutionTest extends \CITest {

    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->data = new \stdClass();
        $this->data->institution_id = 'ins_4';
        $this->data->name = 'Wells Fargo';
    }

    /**
     * @covers Institution::getName
     */
    public function testGetName() {
        $institution = new Institution($this->data);

        $this->assertEquals($this->data->name, $institution->getName());
    }

    /**
     * @covers Institution::getInstitutionId
     */
    public function testGetInstitutionId() {
        $institution = new Institution($this->data);

        $this->assertEquals($this->data->institution_id, $institution->getInstitutionId());
    }
}