# image: gitpod/workspace-full
image:
  file: Dockerfile

# Commands that will run on workspace start
tasks:
    - name: Install php
      before: add-apt-repository ppa:ondrej/php -y
      init: apt update && apt upgrade -y && apt install -y php8.3 libapache2-mod-php8.3 php8.3-{cli,fpm,curl,mysqlnd,gd,opcache,zip,intl,common,bcmath,imagick,xmlrpc,readline,memcached,redis,mbstring,apcu,xml,dom,memcache,pcov,dev}
    - name: Install Apache
      init: apt install apache2 ca-certificates apt-transport-https software-properties-common lsb-release
      command: /usr/sbin/httpd -D FOREGROUND

# Ports to expose on workspace startup
ports:
    - port: 8000
      onOpen: open-browser
      name: Website
      description: Website