image: gitpod/workspace-mysql
# image:
#   file: Dockerfile

# Commands that will run on workspace start
tasks:
    - name: Start Apache
      # init: apt install apache2 ca-certificates apt-transport-https software-properties-common lsb-release
      command: /usr/sbin/httpd -D FOREGROUND

# Ports to expose on workspace startup
ports:
    - port: 8001
      onOpen: open-browser
      name: Website
      description: Website