image: gitpod/workspace-mysql
# image:
#   file: Dockerfile

# Commands that will run on workspace start
tasks:
    - name: Start Apache
      openMode: split-left
      before: echo "gitpod repo root = $GITPOD_REPO_ROOT" && echo "apache docroot in repo = $APACHE_DOCROOT_IN_REPO"
      # init: apt install apache2 ca-certificates apt-transport-https software-properties-common lsb-release
      command: /usr/sbin/httpd -D FOREGROUND
    - name: Start Mysql
      openMode: split-right
      command: mysqld

# Ports to expose on workspace startup
ports:
    - port: 8001
      onOpen: open-browser
      name: Website
      description: Website
    - port: 3306
      name: Database
      description: Database