image: gitpod/workspace-mysql
# image:
#   file: Dockerfile

# Commands that will run on workspace start
tasks:
    - name: Start Apache
      openMode: split-left
      init: sudo apt install net-tools
      before: |
        source /etc/apache2/envvars
        echo $APACHE_SERVER_NAME
      # init: apt install apache2 ca-certificates apt-transport-https software-properties-common lsb-release
      command: /usr/sbin/apache2 -D FOREGROUND

# Ports to expose on workspace startup
ports:
    - port: 8001
      onOpen: open-browser
      name: Website
      description: Website
    - port: 3306
      name: Database
      description: Database